### ISSUE TITLE
OAuthError on callback

### ISSUE THREAD

**Issue by unwitting** [jaredhanson/passport-instagram#11]
Hi, I'm getting the following error when landing back on my /auth/ig/callback:

```
Error
    at Strategy.OAuth2Strategy._createOAuthError (/Users/jack/code/fiiture/node_modules/passport-oauth2/lib/strategy.js:379:17)
    at /Users/jack/code/fiiture/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /Users/jack/code/fiiture/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/Users/jack/code/fiiture/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/jack/code/fiiture/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

The code driving my implementation is:

```
passport.use(new InstagramStrategy({
  clientID: cfg.instagram_api_clientId,
  clientSecret: cfg.instagram_api_clientSecret,
  callbackURL: cfg.instagram_api_authCallback
}, (accessToken, refreshToken, profile, done) => {
  // I don't get here
  console.log(profile)
  console.log(refreshToken)
  console.log(accessToken)
  done(null, profile)
}))
app.get('/auth/ig', passport.authenticate('instagram'))
app.get('/auth/ig/callback', (req, res, next) => {
  // I get here
  log(`Callback`)
  next()
}, passport.authenticate('instagram', { failureRedirect: '/auth/ig' }), (req, res) => {
  res.redirect('/')
})
```

"Callback" is logged but then the failure happens. None of profile, refreshToken or accessToken are logged.

In browser, I land as I would expect on `/auth/ig/callback?code=accesscodenfjnejeneakjv`.

This error's really impenetrable - any guesses as to what's going wrong here?

**Comment by unwitting** [comment]
Ignore me, I can't copy and paste.

**Comment by icyfish** [comment]
@unwitting I have run into the same problem. Would you please tell me how you solved it?
