### ISSUE TITLE
Specific callbackUrl per request to authenticate throws error...

### ISSUE THREAD

**Issue by aniljaangra** [jaredhanson/passport-instagram#16]
Hi guys,

I am Integrating a Instagram authentication to my app. and i have having two different triggering points to authenticate and both have different callbackUrl.

The code driving my implementation is:

```
passport.use(new InstagramStrategy({
  clientID: config.instagram_api_clientId,
  clientSecret: config.instagram_api_clientSecret,
// callbackURL: `http://${config.host}:${config.port}/auth/instagram/login/callback`,
}, (accessToken, refreshToken, profile, done) => {
  // user handling code
  done(null, profile)
}))

router.get('/instagram/signup',
passport.authenticate('instagram', {
    callbackURL: `http://${config.host}:${config.port}/auth/instagram/signup/callback`,
  }),
);

router.get('/instagram/login',
passport.authenticate('instagram', {
    callbackURL: `http://${config.host}:${config.port}/auth/instagram/login/callback`,
  }),
);

router.get('/instagram/:action/callback', passport.authenticate(
  'instagram',
  {
    session: false,
    failureRedirect: '/auth/instagram/login/callback',
    callbackURL: `http://${config.host}:${config.port}/auth/instagram/login/callback`,
  },
), (req, res) => {
  // Successful authentication, redirect home.
  res.redirect(config.client_instagram_redirect_url);
});
```

So As you can see i am calling instagram auth from two endpoints and i am passing the respective callbackUrls but doing this gives me following error.

{"error_type": "OAuthException", "code": 400, "error_message": "Redirect URI doesn't match original redirect URI"}

```
Error
    at Strategy.OAuth2Strategy._createOAuthError (/home/anil/Official/repos/thinksys/influra_backend/node_modules/passport-oauth2/lib/strategy.js:379:17)
    at /home/anil/Official/repos/thinksys/influra_backend/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /home/anil/Official/repos/thinksys/influra_backend/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/anil/Official/repos/thinksys/influra_backend/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/anil/Official/repos/thinksys/influra_backend/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

This works fine if i register the callbackUrl on Stragegy Level by uncommending the callbackUrl and remove the callbackUrl from authenticate call. 
I have all of my callback urls registered in instagram account and these works if i provide at strategy level.
This behaviour works fine with passport-facebook.

essentially what i want to achieve is to know from which action user came i.e. login or signup .
and it is critical for me to get it

**Comment by aniljaangra** [comment]
Sorry guys ... i forgot i needed to have similar callbackUrl in my callback route too.

```
router.get('/instagram/:action/callback', (req, res, next) => passport.authenticate(
  'instagram',
  {
    session: false,
    failureRedirect: '/auth/instagram/callback',
    callbackURL: `http://${config.host}:${config.port}/auth/instagram/${req.params.action}/callback`,
  },
)(req, res, next), (req, res) => {
  // Successful authentication, redirect home.
  res.redirect(`${config.client_instagram_redirect_url}?action=${req.params.action}`);
});
```
