### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by r0mdau** [jaredhanson/passport-instagram#2]
node app.js 

/.../app.js:51
var app = express.createServer();
                  ^
TypeError: Object function createApplication() {
  var app = function(req, res, next) {
    app.handle(req, res, next);
  };

  mixin(app, proto);
  mixin(app, EventEmitter.prototype);

  app.request = { **proto**: req, app: app };
  app.response = { **proto**: res, app: app };
  app.init();
  return app;
} has no method 'createServer'
    at Object.<anonymous> (/.../app.js:51:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by r0mdau** [comment]
The package.json file doesn't contains fixed versions of modules...

**Comment by kevinxh** [comment]
The example is out-dated.

let's update it.

**Comment by Zrce** [comment]
an update would be great. @kevinxh have you found another solution.

**Comment by kevinxh** [comment]
@Zrce I submitted a pull request to update the example.

**Comment by kevinxh** [comment]
@Zrce in the meanwhile just use my forked repo :)

**Comment by pbojinov** [comment]
@jaredhanson Any chance to get this merged? https://github.com/jaredhanson/passport-instagram/pull/5
